install: gradle wrapper --gradle-version 6.1
language: java
jdk:
    - openjdk8

before_install:
    - chmod +x gradlew

branches:
    only:
        - master

cache:
    directories:
        - '$HOME/.gradle'
script: "./gradlew clean build"

notifications:
    slack:
        secure: lOz00LFlKyWP3dJ2QgMnQczuoIHEEzFc70+YcJ61TdaXeJEebnQXzkNDLErK2jENy8lbzkZF6RMiOmPNuUO557fycTLiQyi3V4pnLRQ/TKT4/5xDQmZHLxRP0jmmLMFGlGTrDLLOoMV/41HUIbhPrMyzmHTjVR3mBp0xiM0tPMSpDijnET5zYj21A4TyQjTF0RKla6+QgGJivR4iGYuTxYl5/ceKnDQV5kPI189BVJfqqiM2vF2ZzhsXmTxodReUaa5rpZebAqSwwqfcMNnJ3JqodBeK0AV5yEVBbh1/sNDQC8Fa0cJapwwFJ+OsViESlgwaozJI5tCoKfHllkwekxNMZZJFZ7F0Tc8JdymVEtJgeKyQN7T5+rWAjyQHkMOF1nzAEnvSlmkyWdKIppiGiPbwPbOm16+shKe46b0J/qfpbqt7mxWdoF7c9VWvxM4gIXId8gN+TOOEigKhf0If5lvTdP5bNtq4YSbAkWE8CvsjPkOrWuGZQ/QsYRiFjshspyrdTJI8ollTKkBRWZeviNWwJhheyovfHzomEhUIMXWHzsbzwlPHfxgx9n3y5K7BWOLX7Aq5OKQA+OjMAt4UxKzfsa3BGWxPRTJyWL1RpJhwfHuid0WgYsT2VDucfVVIiqWKxX7vq2VaAyMupnR10rjs/zxCfh1jkR31PPbx6Xo=
