language: java
jdk:
    - openjdk8

branches:
    only:
        - master

cache:
    directories:
        - '$HOME/.gradle'
script: "./gradlew clean build"

notifications:
    slack: mocadevs:0GFPHOOopFep911ZGvAq2eyV
