install: gradle wrapper --gradle-version 6.1
language: java
jdk:
    - openjdk8

before_install:
    - chmod +x gradlew

branches:
    only:
        - master

cache:
    directories:
        - '$HOME/.gradle'
script: "./gradlew clean build"

notifications:
    slack: mocadevs:0GFPHOOopFep911ZGvAq2eyV
